application: wlee-cs373-wc
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /test.*
  script: gaeunit.py

- url: /content
  static_dir: htmlgoodies/content

- url: /images
  static_dir: htmlgoodies/content/images
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: WC3.py

libraries:

- name: django
  version: "1.2"

